### PR TITLE
Convert from Volute

### PR DESCRIPTION
**Pull request by gtaffoni**
I convert the Volute repository to github

### CODE REVIEW

**Comment by Zarquan** [comment]
I think we should exclude the PHP source code directory from the transfer to ivoa-std.

**Comment by gtaffoni** [comment]
> I think we should exclude the PHP source code directory from the transfer to ivoa-std.

Good point Dave, I forgot to remove it in the Volute migration

**Comment by Zarquan** [comment]
Unfortunately deleting them from the pull request means they will still be in the git history, for perpetuity.
If you can wait until September, I'll have a go at creating a new import excluding the PHP source directory, which should mean they don't end up in the git history.

**Comment by Zarquan** [comment]
Replaced by #6

**Pull request closed without merging**
